# ~/.config/starship.toml

add_newline = true
format = "$sudo$time$all$username$hostname$character"
command_timeout = 500 # git is timing out

[aws]
disabled = true

[battery]
full_symbol = "ï•¸ "
charging_symbol = "ï–ƒ "
discharging_symbol = "ï–‚ "

[[battery.display]]
# "bold red" style and discharging_symbol when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]
# "bold yellow" style and ğŸ’¦ symbol when capacity is between 10% and 30%
# when capacity is over 30%, the battery indicator will not be displayed
threshold = 30
style = "bold yellow"
discharging_symbol = "ğŸ’¦ "

[c]
symbol = "î˜ "
detect_extensions = ["c", "c++", "h", "hpp"]

[character]
# prompt character
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ](bold red) "
# vicmd only works with zsh and fish.
vicmd_symbol = "[V](bold green) "

[cmd_duration]
min_time = 10_000  # Show command duration over 10 sec
format = " took [$duration]($style)"
show_notifications = true
min_time_to_notify = 60_000 # Show notification if cmd takes >1m

[conda]
ignore_base = true
symbol = "ğŸ"
style = "dimmed green"
format = "[$symbol$environment]($style) "
disabled = false

[directory]
read_only = " ï ½"
truncate_to_repo = false
truncation_length = 4
truncation_symbol = "â€¦/"
style = "fg:#96ef96"

[docker_context]
symbol = "ïŒˆ "

[git_branch]
format = " [$symbol$branch]($style) "
always_show_remote = true
#ignore_branches = ["master", "main"]

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_metrics]
format = "[+$added]($added_style)/[-$deleted]($deleted_style) "
disabled = false

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
up_to_date = " âœ“"
untracked = "Untracked $count"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[golang]
symbol = "î˜§ "

[haskell]
symbol = "î· "

[hg_branch]
symbol = "ï˜ "

[hostname]
ssh_only = false
format = "@[$hostname]($style) "
style = "dimmed white"
disabled = false

[line_break]
disabled = false

[localip]
disabled = false
ssh_only = true

[memory_usage]
format = "ram: ${ram}($style) "
threshold = 70
style = "bold dimmed white"
disabled = true

[nix_shell]
symbol = "ï‹œ "

[nodejs]
symbol = "îœ˜ "

[package]
disabled = true

[python]
symbol = "îˆµ "
style = "bold bright-blue"
format = '[Â· ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rust]
symbol = "âš™ï¸ "
style = "dimmed #ff3300"
format = "[$symbol$version]($style) "

[sudo]
style = "dimmed green"
symbol = "ğŸ”“"
format = "[$symbol]($style)"
disabled = false

[time]
use_12hr = false
time_format = "%R" # Hour-minute format. Same to %H:%M.
style = "bright-white"
format = "$time($style) "
disabled = false

[username]
show_always = true
format = "[$user]($style)"
style_root = "black bold"
style_user = "bold green"
